# Generated by Django 5.0.4 on 2024-09-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=512)),
                ('class_prediction', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
    ]
