# Generated by Django 5.0.4 on 2024-09-10 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_systems', to=settings.AUTH_USER_MODEL)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
